app_id: "89e19608-864f-4141-be98-dec699d7cac2"
app_secret: "xd73.9yCKyao~-16yeccML7824z.F3PgZ3"
redirect: "http://localhost:8000/callback"
scopes:
  - user.read
  - mailboxsettings.read
  - calendars.readwrite
authority: "https://login.microsoftonline.com/common"